name: profile-summary-cards

on:
  schedule: # execute every 24 hours
    - cron: "5 19 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards

    steps:
      - uses: actions/checkout@v3
      - uses: brinkqiang/github-profile-summary-cards@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          # BRANCH_NAME is optional, default to main, branch name to push cards
          BRANCH_NAME: "master"
          # UTC_OFFSET is optional, default to zero
          UTC_OFFSET: 8
          # EXCLUDE is an optional comma seperated list of languages to exclude, defaults to ""
          EXCLUDE: ""
          # AUTO_PUSH is optional, a boolean variable default to true, whether automatically push generated files to desired branch
          AUTO_PUSH: true

      - name: Print current time
        run: |
          echo "The current UTC time is: $(date -u)"

      - name: Status
        uses: brinkqiang/github-status-action@v2
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Set Status'
          description: 'Passed'
          state: 'success'